CLASS_PATH += target/dependency/

.PHONY: mvn.deepclean

all: target/dependency
deepclean: mvn.deepclean

target/dependency:
	mvn -nsu clean compile dependency:unpack-dependencies generate-sources

mnv.deepclean: target/dependency
	$(RM) $^
